ppw_alifsaddid/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name = 'index.html'), name = 'home'),
    path('story1/', include('story1.urls', namespace='story1')),
    path('story3/', include('story3.urls', namespace='story3')),
    path('story4/', RedirectView.as_view(pattern_name='story3:index'), name='story4'),
    path('story5/', include('story5.urls', namespace='story5')),
    path('story6/', include('story6.urls', namespace='story6')),
    path('story7/', include('story7.urls', namespace='story7')),
    path('story8/', include('story8.urls', namespace='story8')),
    path('auth/', include('userauth.urls', namespace='auth')),
]

story1/urls.py
from django.urls import path
from django.views.generic import TemplateView

urlpatterns = [
	path('', TemplateView.as_view(template_name = 'story1/index.html'), name = 'index')
]

app_name = 'story1'

userauth/urls.py
from django.urls import path
from .views import userlogin, userregister, userlogout

urlpatterns = [
	path('login/', userlogin, name = 'login'),
	path('register/', userregister, name = 'register'),
    path('logout/', userlogout, name = 'logout'),
]

app_name = 'userauth'

userauth/models.py
from django.db import models

# Create your models here.

userauth/forms.py
from django import forms

class AuthForm(forms.Form):
    nama = forms.CharField(
        max_length = 300,
        widget = forms.TextInput(
            attrs = {
                'class': 'form-control',
				'placeholder': 'Masukkan username'
            }
        )
    )

    password = forms.CharField(
        max_length = 100, 
        widget = forms.PasswordInput(
            attrs = {
                'class': 'form-control',
				'placeholder': 'Masukkan password'
            }
        )
    )

userauth/views.py
from django.shortcuts import render, redirect, resolve_url
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User 

from .forms import AuthForm

# Create your views here.
def userlogin(request):
    if (not request.user.is_anonymous):
	    return redirect(resolve_url('story5:index') + '#jadwal')

    form = AuthForm(request.POST or None)
    context = {
        'Form': form,
        'isError': False,
        'Error': '',
    }

    if (request.method == "POST"):
        account = authenticate(
            username = request.POST['nama'],
            password = request.POST['password'],
        )

        if (account == None):
            context['isError'] = True
            context['Error'] = 'Autentikasi gagal'
            context['Form'] = AuthForm()
            return render(request, 'userauth/login.html', context)
        else:
            login(request, account)
            return redirect(resolve_url('story5:index') + '#jadwal')

    return render(request, 'userauth/login.html', context)

def userregister(request):
    if (not request.user.is_anonymous):
	    return redirect(resolve_url('story5:index') + '#jadwal')

    form = AuthForm(request.POST or None)
    context = {
        'Form': form,
        'isError': False,
        'Error': '',
    }

    if (request.method == "POST"):
        acount = None
        try:
            account = User.objects.get(username = request.POST['nama'])
        except:
            account = None
        if (account == None):
            new_account = User.objects.create_user(request.POST['nama'], '', request.POST['password'])
            new_account.save()
            login(request, new_account)
            return redirect(resolve_url('story5:index') + '#jadwal')
        else:
            context['isError'] = True
            context['Error'] = 'Sudah ada akun dengan username ' + request.POST['nama']
            context['Form'] = AuthForm()
            return render(request, 'userauth/register.html', context)

    return render(request, 'userauth/register.html', context)

def userlogout(request):
    logout(request)
    return redirect(resolve_url('userauth:login') + '#login')

userauth/templates/userauth/login.html
{% extends 'story3/base.html' %}

{% block content %}

<section id="login">    
    <h1 class="big-text text-center">Login</h1>
    <div class="container" style="max-width:60%">
        <div class="card">
            <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
            
                    <div class="form-group">
                        <label for="id_nama">Username:</label>
                        {{Form.nama}}
                    </div>
            
                    <div class="form-group">
                        <label for="id_password">Password:</label>
                        {{Form.password}}
                    </div>
                    {% if isError %}
                        <p style="color:red">{{Error}}</p>
                    {% endif %}
                    <button type="submit" class="btn btn-success btn-block">Login</button>
                </form>
                <p>Belum punya akun? <a href="{% url 'auth:register' %}#register">Register</a></p>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

userauth/templates/userauth/register.html
{% extends 'story3/base.html' %}

{% block content %}

<section id="register">    
    <h1 class="big-text text-center">Register</h1>
    <div class="container" style="max-width:60%">
        <div class="card">
            <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
            
                    <div class="form-group">
                        <label for="id_nama">Username:</label>
                        {{Form.nama}}
                    </div>
            
                    <div class="form-group">
                        <label for="id_password">Password:</label>
                        {{Form.password}}
                    </div>
                    {% if isError %}
                        <p style="color:red">{{Error}}</p>
                    {% endif %}
                    <button type="submit" class="btn btn-success btn-block">Register</button>
                    <p>Sudah punya akun? <a href="{% url 'auth:login' %}#login">Login</a></p>
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock content %}