ppw_alifsaddid/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name = 'index.html'), name = 'home'),
    path('story1/', include('story1.urls', namespace='story1')),
    path('story3/', include('story3.urls', namespace='story3')),
    path('story4/', RedirectView.as_view(pattern_name='story3:index'), name='story4'),
    path('story5/', include('story5.urls', namespace='story5')),
    path('story6/', include('story6.urls', namespace='story6')),
    path('story7/', include('story7.urls', namespace='story7')),
    path('story8/', include('story8.urls', namespace='story8')),
    path('auth/', include('userauth.urls', namespace='auth')),
]

story1/urls.py
from django.urls import path
from django.views.generic import TemplateView

urlpatterns = [
	path('', TemplateView.as_view(template_name = 'story1/index.html'), name = 'index')
]

app_name = 'story1'

story6/urls.py
from django.urls import path

from .views import index, tambah, hapus, peserta_tambah, peserta_hapus

urlpatterns = [
	path('', index, name = 'index'),
    path('tambah/', tambah, name = 'tambah'),
    path('hapus/<int:id>/', hapus, name = 'hapus'),
    path('peserta/tambah/', peserta_tambah, name = 'peserta_tambah'),
    path('peserta/hapus/<int:id>/', peserta_hapus, name = 'peserta_hapus'),
]

app_name = 'story6'

story6/models.py
from django.db import models

class Aktivitas(models.Model):
    nama = models.CharField(max_length = 100, default = '')

class Peserta(models.Model):
    nama = models.CharField(max_length = 100, default = '')
    aktivitas = models.ForeignKey(Aktivitas, on_delete = models.CASCADE)

story6/forms.py
from django import forms
from .models import Aktivitas, Peserta

class AktivitasForm(forms.ModelForm):
    class Meta:
        model = Aktivitas 
        fields = [
            'nama'
        ]

        widgets = {
            'nama': forms.TextInput(
                attrs = {
                    'class': 'form-control',
                    'placeholder': 'Masukkan nama aktivitas'
                }
            )
        }

class PesertaForm(forms.ModelForm):
    class Meta:
        model = Peserta
        fields = [
            'nama',
            'aktivitas'
        ]

        widgets = {
            'nama': forms.TextInput(
                attrs = {
                    'class': 'form-control',
                    'placeholder': 'Tambahkan peserta'
                }
            )
        }

story6/views.py
from django.shortcuts import render, redirect, resolve_url
from .models import Aktivitas, Peserta
from .forms import AktivitasForm, PesertaForm

# Create your views here.
def index(request):
    pesertaForm = PesertaForm()
    aktivitasForm = AktivitasForm()
    activities = Aktivitas.objects.all()
    lst = [[i, Peserta.objects.filter(aktivitas = i)] for i in activities]
    context = {
        'activities': lst,
        'Form': pesertaForm,
        'AktivitasForm': aktivitasForm,
    }
    return render(request, 'story6/index.html', context)

def tambah(request):
    form = AktivitasForm(request.POST or None)
    if (request.method == 'POST'):
        if (form.is_valid):
            form.save()
    return redirect(resolve_url('story6:index') + '#index')


def hapus(request, id):
    if (request.method == "GET"):
        return redirect(resolve_url('story6:index') + '#index')

    aktivitas = Aktivitas.objects.get(id = id)
    aktivitas.delete() 
    return redirect(resolve_url('story6:index') + '#index')

def peserta_tambah(request):
    form = PesertaForm(request.POST or None)
    if (request.method == 'POST'):
        if (form.is_valid):
            form.save()
    return redirect(resolve_url('story6:index') + '#index')

def peserta_hapus(request, id):
    if (request.method == "GET"):
        return redirect(resolve_url('story6:index') + '#index')

    peserta = Peserta.objects.get(id = id)
    peserta.delete()
    return redirect(resolve_url('story6:index') + '#index')

story6/templates/story6/index.html
{% extends 'story3/base.html' %}

{% block content %}
<style>
    div.card{
        margin-bottom: 10px;
    }
    
    ul{
        list-style-type: none;
    }

    .no-padding{
        padding: 0 !important;
    }

    .d-flex{
        padding: 0;
    }
</style>

<section id="index">
    <div class="container">
        <h1 class="big-text text-center">Aktivitas</h1>
        <div class="row">
            <div class="col-2">

            </div>
            <div class="col-8">
                <div class="card">
                    <div class="card-body">
                        <h3 class="medium-text text-center">Tambah Aktivitas</h3>
                        <form action="{% url 'story6:tambah' %}" method="POST" id="form-tambah">
                            {% csrf_token %}
                            <div class="form-group">
                                {{AktivitasForm.nama}}
                            </div>
                            <button type="submit" id="tambah" class="btn btn-success btn-block">Tambah</button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-2"></div>
        </div>
        <div class="row">
            {% for aktivitas in activities %}
                <div class="col-12 col-sm-4 col-md-4 d-flex align-item-stretch justify-content-center">
                    <div class="card">
                        <div class="card-body">
                            <form action="{% url 'story6:hapus' aktivitas.0.id %}" method="POST">
                                {% csrf_token %}
                                <button type="submit" class="btn">
                                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                        <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                      </svg>
                                </button>
                            </form>
                            <h3 class="medium-text text-center">{{aktivitas.0.nama}}</h3>
                            <h6 class="card-subtitle mb-2 text-muted">Peserta</h6>
                            <ul>
                                {% for peserta in aktivitas.1 %}
                                    <li>
                                        <div style="display: flex;">
                                            {{peserta.nama}} &nbsp;
                                            <form action="{% url 'story6:peserta_hapus' peserta.id %}" method="POST">
                                                {% csrf_token %}
                                                <button type="submit" class="btn no-padding">
                                                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                                        <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                                      </svg>
                                                </button>
                                            </form>
                                        </div>
                                    </li>
                                {% endfor %}
                            </ul>
                            <form action="{% url 'story6:peserta_tambah' %}" method="POST">
                                {% csrf_token %}
                                <input type="select" hidden name="aktivitas" value="{{aktivitas.0.id}}">
                                <div class="row">
                                    <div class="col-8">
                                        <div class="form-group">
                                            {{Form.nama}}
                                        </div>
                                    </div>
                                    <div class="col-2">
                                        <button type="submit" class="btn btn-success">Tambah</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock content %}

story6/templates/story6/tambah.html
{% extends 'story3/base.html' %}

{% block content %}
<section class="index">
    <div class="container">
        <h1 class="big-text text-center">Tambah</h1>
    </div>
</section>
{% endblock content %}