ppw_alifsaddid/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name = 'index.html'), name = 'home'),
    path('story1/', include('story1.urls', namespace='story1')),
    path('story3/', include('story3.urls', namespace='story3')),
    path('story4/', RedirectView.as_view(pattern_name='story3:index'), name='story4'),
    path('story5/', include('story5.urls', namespace='story5')),
    path('story6/', include('story6.urls', namespace='story6')),
    path('story7/', include('story7.urls', namespace='story7')),
    path('story8/', include('story8.urls', namespace='story8')),
    path('auth/', include('userauth.urls', namespace='auth')),
]

story1/urls.py
from django.urls import path
from django.views.generic import TemplateView

urlpatterns = [
	path('', TemplateView.as_view(template_name = 'story1/index.html'), name = 'index')
]

app_name = 'story1'

story5/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import index, tambah, hapus, edit, detail, delete_tugas

urlpatterns = [
	path('', index, name = 'index'),
	path('tambah/', tambah, name = 'tambah'),
	path('hapus/<int:id>/', hapus, name = 'hapus'),
	path('edit/<int:id>/', edit, name = 'edit'),
	path('detail/<int:id>/', detail, name='detail'),
	path('hapus/tugas/<int:id>', delete_tugas, name='delete_tugas'),
]

app_name = 'story5'

userauth/urls.py
from django.urls import path
from .views import userlogin, userregister, userlogout

urlpatterns = [
	path('login/', userlogin, name = 'login'),
	path('register/', userregister, name = 'register'),
    path('logout/', userlogout, name = 'logout'),
]

app_name = 'userauth'

story5/models.py
from django.db import models
from bs4 import BeautifulSoup
import requests

def get_dosen():
    url = "https://www.cs.ui.ac.id/index.php/staf-pengajar/"
    page = requests.get(url)
    soup = BeautifulSoup(page.text, 'html.parser')
    content = soup.find("div", class_='gdlr-core-pbf-sidebar-content-inner').find_all("div", class_="gdlr-core-pbf-element")[1]
    content = content.find("div", class_="gdlr-core-personnel-item").find_all("div", class_="gdlr-core-personnel-list-column")

    dosen_list = [i.find("div", class_="gdlr-core-personnel-list").find("h3").find("a").text for i in content]
    dosen_list = [(i, i) for i in dosen_list]

    content = soup.find("div", class_='gdlr-core-pbf-sidebar-content-inner').find_all("div", class_="gdlr-core-pbf-element")[2]
    content = content.find("div", class_="gdlr-core-personnel-item").find_all("div", class_="gdlr-core-personnel-list-column")
    another_dosen = [i.find("div", class_="gdlr-core-personnel-list").find("h3").find("a").text for i in content]
    another_dosen = [(i, i) for i in another_dosen]
    dosen_list.extend(another_dosen)

    url = "https://cs.ui.ac.id/staf-pengajar-tidak-tetap/"
    page = requests.get(url)
    soup = BeautifulSoup(page.text, 'html.parser')
    content = soup.find("div", class_='gdlr-core-pbf-sidebar-content-inner').find_all("div", class_="gdlr-core-pbf-element")[1]
    content = content.find("div", class_="gdlr-core-personnel-item").find_all("div", class_="gdlr-core-personnel-list-column")
    another_dosen = [i.find("div", class_="gdlr-core-personnel-list").find("h3").find("a").text for i in content]
    another_dosen = [(i, i) for i in another_dosen]

    dosen_list.extend(another_dosen)
    return dosen_list

# Create your models here.
class Matakuliah(models.Model):
    nama        = models.CharField(max_length = 100)
    dosen       = models.CharField(
                    max_length = 500,
                    choices = get_dosen(),
                    default = 'Prof. Achmad Nizar Hidayanto, S.Kom., M.Kom., Dr.'
    )
    sks         = models.IntegerField()
    deskripsi   = models.CharField(max_length = 1000)
    semester    = models.CharField(
                    max_length = 6,
                    choices = [
                        ('Ganjil', 'Ganjil'),
                        ('Genap', 'Genap')
                    ],
                    default = 'Ganjil'
    )
    tahun       = models.CharField(
                    max_length = 9,
                    choices = [
                        ('2019/2020', '2019/2020'),
                        ('2020/2021', '2020/2021'),
                        ('2021/2022', '2021/2022'),
                        ('2022/2023', '2022/2023'),
                    ],
                    default = '2020/2021'
    )
    ruang       = models.CharField(max_length = 100)
    tugas_tersisa = models.IntegerField(default = 0)

    class Meta:
        ordering = ["-tugas_tersisa", "nama"]

    def __str__(self):
    	return "{}. {}".format(self.id, self.nama)

class Tugas(models.Model):
    nama    = models.CharField(max_length = 100)
    matkul  = models.ForeignKey(Matakuliah, on_delete = models.CASCADE)
    due     = models.DateTimeField()

    def __str__(self):
        return "{}. {}".format(self.id, self.nama)

    class Meta:
        ordering = ["due"]
    

story5/forms.py
from django import forms
from .models import Matakuliah, Tugas

class MatakuliahForm(forms.ModelForm):
	class Meta:
		model = Matakuliah
		fields = [
			'nama',
			'dosen',
			'sks',
			'deskripsi',
			'semester',
			'tahun',
			'ruang'
		]

		widgets = {
			'nama': forms.TextInput(
				attrs = {
					'class': 'form-control',
					'placeholder': 'Masukkan Nama Mata Kuliah'
				}
			),
			'dosen': forms.Select(
				attrs = {
					'class': 'form-control',
					'placeholder': 'Masukkan Nama Dosen Pengajar'
				}
			),
			'sks': forms.NumberInput(
				attrs = {
					'class': 'form-control',
					'placeholder': 'Masukkan Jumlah SKS'
				}
			),
			'deskripsi': forms.Textarea(
				attrs = {
					'class': 'form-control',
					'placeholder': 'Masukkan Deskripsi Mata Kuliah'
				}
			),
			'semester': forms.Select(
				attrs = {
					'class': 'form-control',
				}
			),
			'tahun': forms.Select(
				attrs = {
					'class': 'form-control',
				}
			),
			'ruang': forms.TextInput(
				attrs = {
					'class': 'form-control',
					'placeholder': 'Masukkan Ruang Kelas Kuliah'
				}
			)
		}

class TugasForm(forms.ModelForm):
	class Meta:
		model = Tugas
		fields = [
			'nama',
			'matkul',
			'due'
		]

		widgets = {
			'nama': forms.TextInput(
				attrs = {
					'class': 'form-control',
					'placeholder': 'Masukkan Nama Tugas'
				}
			),
			'due': forms.DateTimeInput(
				attrs = {
					'class': 'form-control',
					'type': 'datetime-local'
				}
			)
		}

story5/views.py
from django.shortcuts import render, redirect, resolve_url
from django.urls import reverse
from django.utils import timezone
from .models import Matakuliah, Tugas
from .forms import MatakuliahForm, TugasForm
from math import ceil
import datetime
import pytz

allHari = ["Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu", "Minggu"]

# Create your views here.
def index(request):
	allMatakuliah = Matakuliah.objects.all()
	allTugas = Tugas.objects.all()
	now = datetime.datetime.now(timezone.utc)
	now += datetime.timedelta(hours = 7)
	for tugas in allTugas:
		if (tugas.due < now):
			tugas.matkul.tugas_tersisa -= 1
			tugas.matkul.save()
			tugas.delete()
	hari = [allHari[(now + datetime.timedelta(i)).weekday()] for i in range(0, 12)]
	tanggal = [str((now + datetime.timedelta(i)).day) + '/' + str((now + datetime.timedelta(i)).month) for i in range(0, 12)] 
	delta = [(i.due - now, i.due - now, i.nama) for i in allTugas]
	delta = [[min(i.days + 1 + (1 if ((now + datetime.timedelta(seconds = i.seconds)).weekday() != now.weekday()) else 0), 12), j.days + 1, k] for i, j, k in delta]
	for i in delta:
		if (i[1] <= 2):
			i[1] = "linear-gradient(to right, #D45769, #D45769, #F9AD6A)"
		elif (i[1] <= 4):
			i[1] = "linear-gradient(to right, #F9AD6A, #F9AD6A, #F9E07F)"
		elif (i[1] <= 7):
			i[1] = "linear-gradient(to right, #F9E07F, #F9E07F, #7BE495)"
		else:
			i[1] = "linear-gradient(to right, #7BE495, #7BE495, #86E3CE)"
	context = {
		'allMatakuliah': allMatakuliah,
		'allTugas': delta,
		'allHari': hari,
		'allTanggal': tanggal,
	}
	return render(request, 'story5/index.html', context)

def tambah(request):
	if (request.user.is_anonymous):
		return redirect(resolve_url('userauth:login') + '#login')

	form = MatakuliahForm(request.POST or None)

	if (request.method == "POST"):
		if (form.is_valid()):
			form.save()
		return redirect(resolve_url('story5:index') + '#jadwal')

	context = {
		'Form': form,
	}

	return render(request, 'story5/tambahMatkul.html', context)

def hapus(request, id):
	if (request.user.is_anonymous):
		return redirect(resolve_url('userauth:login') + '#login')
	
	try:
		matkul = Matakuliah.objects.get(id = id)

		if (request.method == "POST"):
			matkul.delete()
			return redirect(resolve_url('story5:index') + '#jadwal')

		context = {
			'matkul': matkul
		}
		return render(request, 'story5/deleteMatkul.html', context)
	except:
		return redirect(resolve_url('story5:index') + '#jadwal')

def edit(request, id):
	if (request.user.is_anonymous):
		return redirect(resolve_url('userauth:login') + '#login')

	matkul = Matakuliah.objects.get(id = id)
	form = MatakuliahForm(initial = {
		'nama': matkul.nama,
		'dosen': matkul.dosen,
		'sks': matkul.sks,
		'deskripsi': matkul.deskripsi,
		'semester': matkul.semester,
		'tahun': matkul.tahun,
		'ruang': matkul.ruang
	}, instance = matkul)

	if (request.method == "POST"):
		form = MatakuliahForm(request.POST, instance = matkul)
		if (form.is_valid()):
			form.save()
		return redirect(resolve_url('story5:index') + '#jadwal')

	context = {
		'Form': form,
	}

	return render(request, 'story5/editMatkul.html', context)

def detail(request, id):
	form = TugasForm(request.POST or None)
	matkul = Matakuliah.objects.get(id = id)
	all_tugas = Tugas.objects.filter(matkul = matkul)
	if (request.method == "POST"):
		now = datetime.datetime.now()
		timeNow = str(now)
		if (timeNow < " ".join(request.POST['due'].split("T"))):
			if (form.is_valid):
				matkul.tugas_tersisa += 1
				matkul.save()
				form.save()
		form = TugasForm()

	context = {
		'matkul': matkul,
		'Form': form,
		'Tugas': all_tugas,
	}

	return render(request, 'story5/detailMatkul.html', context)

def delete_tugas(request, id):
	tugas = Tugas.objects.get(id = id)
	if (request.method == "POST"):
		matkul = tugas.matkul
		matkul.tugas_tersisa -= 1
		matkul.save()
		tugas.delete()
	return redirect('story5:detail', id = tugas.matkul.id)
	

story5/templates/story5/deleteMatkul.html
{% extends 'story3/base.html' %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'story5/css/style.css' %}">

<section id="delete">
	<div class="container">
        <h1 class="big-text text-center">Hapus {{matkul.nama}}</h1>
        <div class="card">
            <div class="card-header text-center">
                <h3 class="medium-text text-center">Yakin menghapus {{matkul.nama}}?</h3>
            </div>
            <div class="card-body">
                <h5 class="card-title">Deskripsi</h5>
                <p>{{matkul.deskripsi}}</p>
                <br>
                <h5 class="card-title">Dosen Pengampu</h5>
                <p>{{matkul.dosen}}</p>
                <br>
                <h5 class="card-title">Bobot</h5>
                <p>{{matkul.sks}} SKS</p>
                <br>
                <h5 class="card-title">Semester</h5>
                <p>{{matkul.semester}} {{matkul.tahun}}</p>
                <br>
                <h5 class="card-title">Ruang Kelas</h5>
                <p>{{matkul.ruang}}</p>
                <br>
                <form method="POST">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-6">
                            <button type="submit" class="btn btn-danger btn-block">Hapus</button>
                        </div>
                        <div class="col-6">
                            <a href="{% url 'story5:index' %}#jadwal" class="btn btn-warning btn-block">Cancel</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

story5/templates/story5/detailMatkul.html
{% extends 'story3/base.html' %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'story5/css/style.css' %}">

<section id="detail">
	<div class="container">
		<h1 class="big-text text-center">{{matkul.nama}}</h1>
		<div class="card">
          <div class="card-body">
              <div class="icon-matkul">
                <a href="{% url 'story5:edit' matkul.id %}#edit" data-toggle="tooltip" data-placement="top" title="Edit">
                  <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                    <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                  </svg>
                </a>
                <a href="{% url 'story5:hapus' matkul.id %}#delete" data-toggle="tooltip" data-placement="top" title="Hapus">
                  <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5a.5.5 0 0 0-1 0v7a.5.5 0 0 0 1 0v-7z"/>
                  </svg>
                </a>
              </div>
              <h5 class="card-title">Deskripsi</h5>
              <p>{{matkul.deskripsi}}</p>
              <br>
              <h5 class="card-title">Dosen Pengampu</h5>
              <p>{{matkul.dosen}}</p>
              <br>
              <h5 class="card-title">Bobot</h5>
              <p>{{matkul.sks}} SKS</p>
              <br>
              <h5 class="card-title">Semester</h5>
              <p>{{matkul.semester}} {{matkul.tahun}}</p>
              <br>
              <h5 class="card-title">Ruang Kelas</h5>
              <p>{{matkul.ruang}}</p>
              <br>
              <a href="{% url 'story5:index' %}#jadwal" class="btn btn-primary">Kembali ke Jadwal</a>
          </div>
      </div>
  </div>
  
  <div class="container">
    <h1 class="big-text text-center">Tugas</h1>
    <div id="tugas" class="tugas" style="display: flex; flex-direction: column; justify-content: center; align-items: center;">
      <div class="card" style="width: 50%">
        <div class="card-body">
            <form method="POST">
              {% csrf_token %}
              <div class="form-group">
                <label for="id_nama">Masukkan Nama Tugas:</label>
                {{Form.nama}}
              </div>
              <div class="form-group">
                <label>Masukkan Deadline Tugas:</label>
                {{Form.due}}
              </div>
              <input type="select" name="matkul" value="{{matkul.id}}" hidden>
              <button type="submit" class="btn btn-success btn-block">Tambahkan Tugas</button>
            </form>
        </div>
      </div>
    </div>
    <div class="row">
      {% for t in Tugas %}
        <div class="col-6 col-sm-4 col-md-4">
          <div class="card" style="margin-top: 20px">
            <div class="card-header">
              <h3 class="medium-text center">{{t.nama|truncatechars:10}}</h3>
            </div>
            <div class="card-body">
              <p>Deadline: {{t.due}}</p>
              <form action="{% url 'story5:delete_tugas' t.id %}" method="POST">
                {% csrf_token %}
                <button type="submit" class="btn btn-success btn-block">Sudah Selesai</button>
              </form>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
</section>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script>
	$(document).ready(function(){
	  $('[data-toggle="tooltip"]').tooltip();
	});
</script>

{% endblock content %}

story5/templates/story5/editMatkul.html
{% extends 'story3/base.html' %}

{% block content %}

<section id="edit">
	<div class="container">
		<h1 class="big-text text-center">Edit Mata Kuliah</h1>
		<form method="POST">
			{% csrf_token %}
			<div class="form-group">
				<label for="id_nama">Nama Mata Kuliah:</label>
				{{Form.nama}}
			</div>
			<div class="form-group">
				<label for="id_dosen">Nama Dosen Pengampu:</label>
				{{Form.dosen}}
			</div>
			<div class="form-group">
				<label for="id_sks">Jumlah SKS:</label>
				{{Form.sks}}
			</div>
			<div class="form-group">
				<label for="id_deskripsi">Deskripsi Mata Kuliah:</label>
				{{Form.deskripsi}}
			</div>
			<div class="row">
				<div class="col-6">
					<div class="form-group">
						<label for="id_semester">Semester:</label>
						{{Form.semester}}
					</div>
				</div>
				<div class="col-6">
					<div class="form-group">
						<label for="id_semester">Periode:</label>
						{{Form.tahun}}
					</div>
				</div>
			</div>
			<div class="form-group">
				<label for="id_ruang">Ruang Kuliah:</label>
				{{Form.ruang}}
			</div>
			<button type="submit" class="btn btn-success">Simpan Perubahan</button>
			<a href="{% url 'story5:index' %}#jadwal" class="btn btn-danger">Cancel</a>
		</form>
	</div>
</section>


{% endblock content %}

story5/templates/story5/index.html
{% extends 'story3/base.html' %}

{% block content %}

{% load static %}

<link rel="stylesheet" href="{% static 'story5/css/style.css' %}">

<section id="jadwal">
	<h1 class="big-text text-center">Jadwal</h1>
	{% if user.is_authenticated %}
		<h3 class="big-text text-center">
			Selamat datang, {{user.username}}
		</h3>
	{% endif %}
	<div class="container">
		{% if user.is_authenticated %}
			<a style="margin-bottom: 10px;" href="{% url 'story5:tambah' %}#tambah" class="btn btn-success rounded">+</a>
			<a style="margin-bottom: 10px;" href="{% url 'userauth:logout' %}" class="btn btn-danger float-right">Logout</a>
		{% else %}
			<a style="margin-bottom: 10px;" href="{% url 'userauth:login' %}" class="btn btn-success">Login</a>
		{% endif %}
		{% for matkul in allMatakuliah %}
			<div class="card" style="width: 100%; margin-bottom: 10px">
			  <div class="card-header">
				<div>
					<h3 style="display: inline;">
						{{matkul.nama}}
					</h3>
					{% if matkul.tugas_tersisa > 0 %}
						<h6 style="display: inline;"><span class="badge badge-danger">{{matkul.tugas_tersisa}}</span></h6>
					{% endif %}
				</div>
				{% if user.is_authenticated %}
					<div style='max-width: 50px; display: flex; justify-content: space-between;'>
						<a href="{% url 'story5:edit' matkul.id %}#edit" data-toggle="tooltip" data-placement="top" title="Edit">
							<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
								<path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
								<path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
							</svg>
						</a>
						<a href="{% url 'story5:hapus' matkul.id %}#delete" data-toggle="tooltip" data-placement="top" title="Hapus">
							<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
								<path fill-rule="evenodd" d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5a.5.5 0 0 0-1 0v7a.5.5 0 0 0 1 0v-7z"/>
							</svg>
						</a>
					</div>
				{% endif %}
			  </div>
			  <ul class="list-group list-group-flush">
			    <li class="list-group-item">
					<p>
						{% if matkul.deskripsi|length > 100 %}
							{{matkul.deskripsi|truncatechars:150}} <a href="{% url 'story5:detail' matkul.id %}#detail">baca selengkapnya</a>
						{% else %}
							{{matkul.deskripsi}}
						{% endif %}	
					</p>
			    	<p>Dosen: {{matkul.dosen}}</p>
					<p>Ruang Kelas: {{matkul.ruang}}</p>
					<a href="{% url 'story5:detail' matkul.id %}#detail" class="btn btn-primary">Detail</a>
				</li>
			  </ul>
			</div>
		{% endfor %}
		{% if allTugas|length > 0 %}
			<div class="big-screen-only">
				<h1 class="big-text text-center">Tugas Tersisa</h1>
				<div>
					<div class="row">
						{% for tanggal in allTanggal %}
							<div class="col-1">
								{{tanggal}}
							</div>
						{% endfor %}
					</div>
					<div class="row">
						{% for hari in allHari %}
							<div class="col-1">
								{{hari}}
							</div>
						{% endfor %}
					</div>
				</div>
					{% for tugas in allTugas %}
						<div class="row" style="margin-bottom: 10px;">
							<div class="col-{{tugas.0}} tugas-item" style="text-align: center; background: {{tugas.1}};">
								{% if tugas.0 == 1 %}
									{{tugas.2|truncatechars:7}}
								{% else %}
									{{tugas.2|truncatechars:15}}
								{% endif %}
							</div>
						</div>
					{% endfor %}
				</div>
			</div>
		{% endif %}
	</div>
</section>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script>
	$(document).ready(function(){
	  $('[data-toggle="tooltip"]').tooltip();
	});
</script>
	

{% endblock content %}

story5/templates/story5/tambahMatkul.html
{% extends 'story3/base.html' %}

{% block content %}

<section id="tambah">
	<div class="container">
		<h1 class="big-text text-center">Tambah Mata Kuliah</h1>
		<form method="POST">
			{% csrf_token %}
			<div class="form-group">
				<label for="id_nama">Nama Mata Kuliah:</label>
				{{Form.nama}}
			</div>
			<div class="form-group">
				<label for="id_dosen">Nama Dosen Pengampu:</label>
				{{Form.dosen}}
			</div>
			<div class="form-group">
				<label for="id_sks">Jumlah SKS:</label>
				{{Form.sks}}
			</div>
			<div class="form-group">
				<label for="id_deskripsi">Deskripsi Mata Kuliah:</label>
				{{Form.deskripsi}}
			</div>
			<div class="row">
				<div class="col-6">
					<div class="form-group">
						<label for="id_semester">Semester:</label>
						{{Form.semester}}
					</div>
				</div>
				<div class="col-6">
					<div class="form-group">
						<label for="id_semester">Periode:</label>
						{{Form.tahun}}
					</div>
				</div>
			</div>
			<div class="form-group">
				<label for="id_ruang">Ruang Kuliah:</label>
				{{Form.ruang}}
			</div>
			<button type="submit" class="btn btn-success">Tambah Mata Kuliah</button>
			<a href="{% url 'story5:index' %}#jadwal" class="btn btn-danger">Cancel</a>
		</form>
	</div>
</section>


{% endblock content %}