ppw_alifsaddid/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name = 'index.html'), name = 'home'),
    path('story1/', include('story1.urls', namespace='story1')),
    path('story3/', include('story3.urls', namespace='story3')),
    path('story4/', RedirectView.as_view(pattern_name='story3:index'), name='story4'),
    path('story5/', include('story5.urls', namespace='story5')),
    path('story6/', include('story6.urls', namespace='story6')),
    path('story7/', include('story7.urls', namespace='story7')),
    path('story8/', include('story8.urls', namespace='story8')),
    path('auth/', include('userauth.urls', namespace='auth')),
]

story1/urls.py
from django.urls import path
from django.views.generic import TemplateView

urlpatterns = [
	path('', TemplateView.as_view(template_name = 'story1/index.html'), name = 'index')
]

app_name = 'story1'

story3/urls.py
from django.urls import path
from django.views.generic import TemplateView

urlpatterns = [
	path('', TemplateView.as_view(template_name = 'story3/index.html'), name = 'index'),
	path('gallery/', TemplateView.as_view(template_name = 'story3/gallery.html'), name = 'gallery'),
]

app_name = 'story3'

story3/views.py
from django.shortcuts import render

# Create your views here.

story3/templates/story3/snippets/footer.html
<!-- Footer Part -->
<section id="footer" class="bg-footer">
    <footer>
        <div class="container center-element-col">
            <p class="">Get in touch with me at</p>
            <div class="sosmed">
                <a href="https://web.facebook.com/muhammadalifsaddid.prasojo" class="" target="_blank">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#1bcb85" d="M22.675 0h-21.35c-.732 0-1.325.593-1.325 1.325v21.351c0 .731.593 1.324 1.325 1.324h11.495v-9.294h-3.128v-3.622h3.128v-2.671c0-3.1 1.893-4.788 4.659-4.788 1.325 0 2.463.099 2.795.143v3.24l-1.918.001c-1.504 0-1.795.715-1.795 1.763v2.313h3.587l-.467 3.622h-3.12v9.293h6.116c.73 0 1.323-.593 1.323-1.325v-21.35c0-.732-.593-1.325-1.325-1.325z"></path></svg>
                </a>
                <a href="https://www.instagram.com/alifsaddid" class="" target="_blank">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#1bcb85" d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zm0-2.163c-3.259 0-3.667.014-4.947.072-4.358.2-6.78 2.618-6.98 6.98-.059 1.281-.073 1.689-.073 4.948 0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98-1.281-.059-1.69-.073-4.949-.073zm0 5.838c-3.403 0-6.162 2.759-6.162 6.162s2.759 6.163 6.162 6.163 6.162-2.759 6.162-6.163c0-3.403-2.759-6.162-6.162-6.162zm0 10.162c-2.209 0-4-1.79-4-4 0-2.209 1.791-4 4-4s4 1.791 4 4c0 2.21-1.791 4-4 4zm6.406-11.845c-.796 0-1.441.645-1.441 1.44s.645 1.44 1.441 1.44c.795 0 1.439-.645 1.439-1.44s-.644-1.44-1.439-1.44z"></path></svg>
                </a>
                <a href="https://www.linkedin.com/in/alifsaddid/" class="" target="_blank">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#1bcb85" d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-11h3v11zm-1.5-12.268c-.966 0-1.75-.79-1.75-1.764s.784-1.764 1.75-1.764 1.75.79 1.75 1.764-.783 1.764-1.75 1.764zm13.5 12.268h-3v-5.604c0-3.368-4-3.113-4 0v5.604h-3v-11h3v1.765c1.396-2.586 7-2.777 7 2.476v6.759z"></path></svg>
                </a>
                <a href="https://gitlab.com/AlifSaddid" class="" target="_blank">
                    <svg aria-hidden="true" data-prefix="fab" width="24" height="24" data-icon="gitlab" class="svg-inline--fa fa-gitlab fa-w-16 fa-lg " role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                        <path fill="#1bcb85" d="M29.782 199.732L256 493.714 8.074 309.699c-6.856-5.142-9.712-13.996-7.141-21.993l28.849-87.974zm75.405-174.806c-3.142-8.854-15.709-8.854-18.851 0L29.782 199.732h131.961L105.187 24.926zm56.556 174.806L256 493.714l94.257-293.982H161.743zm349.324 87.974l-28.849-87.974L256 493.714l247.926-184.015c6.855-5.142 9.711-13.996 7.141-21.993zm-85.404-262.78c-3.142-8.854-15.709-8.854-18.851 0l-56.555 174.806h131.961L425.663 24.926z"></path>
                    </svg>
                </a>
            </div>
        </div>
    </footer>
</section>
<!-- End of Footer Part -->

story3/templates/story3/snippets/jumbotron.html
<!-- Jumbotron Part -->
<section id = "jumbotron">
    <div class="jumbo">
        <div class="jumbotron-text">
            <p class="text-white"><i>Hey, I'm</i></p>
            <div class="buffer">
                <h1 class="text-white">ALIF SADDID</h1>
            </div>
        </div>
    </div>
</section>
<!-- End of Jumbotron Part -->

story3/templates/story3/snippets/navbar.html
<!-- Navbar Part -->
<nav class="navbar navbar-expand-md text-white navbar-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'story3:index' %}#profile">Profile</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'story3:index' %}#experiences">Experience</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'story3:index' %}#abilities">Abilities</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'story3:index' %}#projects">Projects</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'story3:index' %}#hobbies">Hobbies</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="https://drive.google.com/file/d/1GGCUQbQLGUdgvWRsJdiR_BFX-sYDeZAb/view?usp=sharing" target="_blank">Resume</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="http://alifsaddid.herokuapp.com/blog/" target="_blank">Blog</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'story3:gallery' %}">Gallery</a>
            </li>
        </ul>
    </div>
</nav>
<!-- End of Navbar part -->

story3/templates/story3/snippets/scripts.html
{% load static %}
<script type="text/javascript" src="{% static 'vendor/jquery/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'vendor/popper/popper.js' %}"></script>
<script type="text/javascript" src="{% static 'vendor/bootstrap/bootstrap.js' %}"></script>
<script type="text/javascript" src="{% static 'story3/js/script-navbar.js' %}"></script>

story3/templates/story3/snippets/styles.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'story3/css/style.css' %}">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,400;0,600;0,700;1,400&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap" rel="stylesheet">